#ifndef DEFINE_VARS_H_
#define DEFINE_VARS_H_

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define BLOCK_WIDTH 128
#define BLOCK_HEIGHT 32

#define BLOCK_COLUMN_MAX (WINDOW_WIDTH / BLOCK_WIDTH)
#define BLOCK_ROW_MAX 6

#define PADDLE_WIDTH 128
#define PADDLE_HEIGHT 32

#define BALL_SCALE 8
#define BALL_SPEED (WINDOW_HEIGHT / 1800.0f)

#endif
